openapi: 3.0.0
info:
  contact:
    email: foo@bar.com
  title: Test routing
  version: 1.0.0
  description: foo
servers:
- url: https://d5dbviil0fcgratkcgrn.apigw.yandexcloud.net
- url: https://cdn.ycld.ru
- url: https://media.nikolaymatrosov.ru
tags:
  - name: foo
  - name: any

paths:
  /sosisa:
    get:
      operationId: get-sosisa
      description: dmmy
      tags:
        - "foo"
      x-yc-apigateway-integration:
        type: dummy
        content:
          '*': i'm sosisa
        http_code: 200
        http_headers:
          Content-Type: text/plain
      responses:
          "200":
            description: foo

  /{path+}:
    x-yc-apigateway-any-method:
      operationId: get-anything
      description: foo
      tags:
        - "any"
      x-yc-apigateway-integration:
        type: dummy
        content:
          '*': hello from root wildcard
        http_code: 200
        http_headers:
          Content-Type: text/plain
      parameters:
      - explode: false
        in: path
        required: true
        name: path
        style: simple
        schema:
          type: string
      responses:
        "200":
          descripton: Ok
components:
  securitySchemes:
    httpBasicAuth:
      type: http
      scheme: basic
      x-yc-apigateway-authorizer:
        type: function
        function_id: foo
        tag: "$latest"
        service_account_id: foo
        authorizer_result_ttl_in_seconds: 30

